version: "3.7"
services:
  test-api:
    build:
      context: ./docker
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - '${API_PORT}:8000'
networks:
  default:
    name: test-network